#!/bin/sh
set -e

install -d \
    parts/virtual/bootstrap/lib \
    parts/virtual/bootstrap/bin

PYTHONPATH=parts/virtual/bootstrap/lib \
    easy_install \
    --install-dir=parts/virtual/bootstrap/lib \
    --script-dir=parts/virtual/bootstrap/bin \
    --allow-hosts=nothing.invalid \
    downloads/dist/virtualenv-1.3.3.tar.gz

PYTHONPATH=parts/virtual/bootstrap/lib \
    ./parts/virtual/bootstrap/bin/virtualenv \
    --no-site-packages parts/virtual

./parts/virtual/bin/easy_install \
    --allow-hosts=nothing.invalid \
    downloads/dist/zc.buildout-1.2.1.tar.gz
./parts/virtual/bin/buildout bootstrap
./bin/buildout \
    buildout:offline=false \
    buildout:newest=false \
    buildout:allow-hosts=nothing.invalid \
    "$@"
